### ISSUE TITLE
Исключения для  CV части

### ISSUE THREAD

**Issue by KOTOBOPOT** [KOTOBOPOT/Queue-Analyzer#17]
Добавить кастомные исключения для библиотеки computer_vision

**Comment by TimofeyTst** [comment]
Я рекомендую в таких случаях делать кастомную ошибку, как та DBAccessException, которую ты получил при попытке скомпилировать проект из неправильной папки. Мы с Тимофеем уже попадались на это, когда продолжение работы малозначимой функции приводила к трудно отлавливаемому багу. Можешь пример у меня пример посмотреть.

_Originally posted by @DaMagus26 in https://github.com/KOTOBOPOT/Queue_Analyser_back/pull/9#discussion_r1193164700_

              Тот же коммент про исключения

_Originally posted by @DaMagus26 in https://github.com/KOTOBOPOT/Queue_Analyser_back/pull/9#discussion_r1193169382_
